name: Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build_x86:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            artifact_name: DataToSheets-Linux-x86_64
            pyinstaller_args: --onefile --name DataToSheets src/bot.py
          - os: macos-latest
            artifact_name: DataToSheets-macOS-x86_64
            pyinstaller_args: --onefile --name DataToSheets src/bot.py
          - os: windows-latest
            artifact_name: DataToSheets-Windows-x86_64.exe
            pyinstaller_args: --onefile --name DataToSheets --noconsole src/bot.py

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt  # Percorso modificato per la tua struttura
          pip install pyinstaller

      - name: Build executable
        run: pyinstaller ${{ matrix.pyinstaller_args }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.artifact_name }}
          path: dist/DataToSheets*

  build_arm:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13-arm64, ubuntu-22.04-arm64]
        include:
          - os: macos-13-arm64
            artifact_name: DataToSheets-macOS-arm64
            pyinstaller_args: --onefile --name DataToSheets src/bot.py
          - os: ubuntu-22.04-arm64
            artifact_name: DataToSheets-Linux-arm64
            pyinstaller_args: --onefile --name DataToSheets src/bot.py

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt
          pip install pyinstaller

      - name: Build executable
        run: pyinstaller ${{ matrix.pyinstaller_args }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: dist/DataToSheets*
