name: Build and Release (x86 with Icons)

on:
  push:
    tags:
      - "v*" # Trigger per tutte le versioni (es: v1.0.0)

jobs:
  linux_x86:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt
          pip install pyinstaller

      - name: Build Linux executable
        run: |
          pyinstaller \
            --onefile \
            --name DataToSheets \
            --icon=src/assets/icons/bot_icon.png \
            --add-data="src/assets/icons/bot_icon.png:assets/icons" \
            src/bot.py

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: DataToSheets-Linux-x86_64
          path: dist/DataToSheets*

  macos_x86:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt
          pip install pyinstaller

      - name: Build macOS executable
        run: |
          pyinstaller \
            --onefile \
            --name DataToSheets \
            --icon=src/assets/icons/bot_icon.icns \
            --add-data="src/assets/icons/bot_icon.icns:assets/icons" \
            --osx-bundle-identifier com.yourcompany.DataToSheets \
            src/bot.py

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: DataToSheets-macOS-x86_64
          path: dist/DataToSheets*

  windows_x86:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt
          pip install pyinstaller

      - name: Build Windows executable
        shell: cmd
        run: |
          pyinstaller ^
            --onefile ^
            --name DataToSheets ^
            --icon=src/assets/icons/bot_icon.ico ^
            --add-data="src/assets/icons/bot_icon.ico;assets/icons" ^
            --noconsole ^
            src/bot.py

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: DataToSheets-Windows-x86_64.exe
          path: dist/DataToSheets.exe
